name: Ruby
on:
  pull_request:
    branches:
    - master
jobs:
  run_spec:
    name: Run test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Set up Ruby 2.7
      # actions/checkoutリポジトリのaction.ymlを利用する
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Set up Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install -g yarn && yarn
    - name: Test with test
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
        bin/rails test