name: Ruby
on:
  pull_request:
    branches:
    - master
jobs:
  run_spec:
    name: Run test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      # actions/checkoutリポジトリのaction.ymlを利用する
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Test with test
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
        bin/rails test